---
deployment:
  tasks:
    - export DEPLOYPATH=/home/mediapas/public_html/aaleyceylon.com/
    - /bin/cp -R app $DEPLOYPATH
    - /bin/cp -R public $DEPLOYPATH
    - /bin/cp -R resources $DEPLOYPATH
    - /bin/cp -R routes $DEPLOYPATH
